default:
    trainer: ppo    
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 256
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 16e6
    memory_size: 256
    normalize: true
    num_epoch: 3
    num_layers: 3
    time_horizon: 1000
    sequence_length: 64
    summary_freq: 80000
    use_recurrent: false
    behavioral_cloning:
        demo_path: ../Assets/Demonstrations/ROMAN_Expert_Push_Demo_N20.demo
        strength: 0.5
        steps: 800000
    reward_signals:
        extrinsic:
            strength: 0.1
            gamma: 0.99
        gail:
            strength: 1.0
            gamma: 0.99
            encoding_size: 128
            use_actions: false
            demo_path: ../Assets/Demonstrations/ROMAN_Expert_Push_Demo_N20.demo